#!/usr/bin/env bash

main() {
  declare hugo_publish_dir=public

  declare stork_config_file=stork.json    # generated by hugo
  declare stork_index_file=site.st.json   # generated by stork (json suffix will trigger gzip/br compression)

  declare stork_arch=stork-ubuntu-20-04
  declare stork_releases=https://files.stork-search.net/releases
  declare stork_version=1.4.1

  declare stork_exec=${stork_arch}-${stork_version}
  declare stork_url=${stork_releases}/v${stork_version}/${stork_arch}

  if [[ ! -f "${stork_exec}" ]]; then
    wget --no-verbose "${stork_url}" ||
      { echo "Error: unable to wget ${stork_url}"; exit 1; }
    mv "${stork_arch}" "${stork_exec}" ||
      { echo "Error: unable to mv ${stork_arch} ${stork_exec}"; exit 1; }
    chmod +x "${stork_exec}" ||
      { echo "Error: unable to chmod ${stork_exec}"; exit 1; }
  fi

  hugo --gc --minify ||
    { echo "Error: unable to run hugo"; exit 1; }
  ./${stork_exec} build --input "${hugo_publish_dir}/${stork_config_file}" --output "${hugo_publish_dir}/${stork_index_file}" ||
    { echo "Error: unable to run stork"; exit 1; }
}

set -euo pipefail
main "$@"
