[build]
command = './build.sh'

[build.environment]
HUGO_VERSION = "0.114.0"
DART_SASS_VERSION = "1.63.5"
STORK_VERSION = "1.5.0"
HUGO_BASEURL = 'https://hugo-stork.netlify.app/'
TZ = "America/Los_Angeles"
